// <auto-generated />
using Dmail.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dmail.Data.Migrations
{
    [DbContext(typeof(DmailDbContext))]
    partial class DmailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dmail.Data.Entities.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("SentOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor lorem at auctor cursus. Nunc gravida tincidunt mauris, non laoreet magna gravida vitae. Nullam tempor consequat sem, id iaculis ante tristique a. Pellentesque fringilla mattis molestie. Nunc eu ante a urna feugiat congue. Donec volutpat nisi eu libero commodo, a.",
                            SenderId = 3,
                            SentOn = "2023-01-06",
                            StartDate = "",
                            Title = "Prijava za sponzora",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor lorem at auctor cursus. Nunc gravida tincidunt mauris, non laoreet magna gravida vitae. Nullam tempor consequat sem, id iaculis ante tristique a. Pellentesque fringilla mattis molestie. Nunc eu ante a urna feugiat congue. Donec volutpat nisi eu libero commodo, a.",
                            SenderId = 3,
                            SentOn = "2023-01-05",
                            StartDate = "",
                            Title = "Upit",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor lorem at auctor cursus. Nunc gravida tincidunt mauris, non laoreet magna gravida vitae. Nullam tempor consequat sem, id iaculis ante tristique a. Pellentesque fringilla mattis molestie. Nunc eu ante a urna feugiat congue. Donec volutpat nisi eu libero commodo, a.",
                            SenderId = 3,
                            SentOn = "2023-01-04",
                            StartDate = "",
                            Title = "Dodatne informacije",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "",
                            SenderId = 7,
                            SentOn = "2022-12-06",
                            StartDate = "2022-12-07",
                            Title = "Sastanak 1",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "",
                            SenderId = 4,
                            SentOn = "2022-12-10",
                            StartDate = "2022-12-10",
                            Title = "Sastanak 2",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "",
                            SenderId = 16,
                            SentOn = "2022-12-17",
                            StartDate = "2022-12-16",
                            Title = "Uredivanje prostora",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "",
                            SenderId = 2,
                            SentOn = "2022-12-29",
                            StartDate = "2022-12-20",
                            Title = "Predavanje 5",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.SpamAdress", b =>
                {
                    b.Property<int>("User1Id")
                        .HasColumnType("integer");

                    b.Property<int>("User2Id")
                        .HasColumnType("integer");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("SpamAdresses");
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jadrankalovric@gmail.com",
                            FirstName = "Jadranka",
                            LastName = "Lovrić",
                            Password = "QJpzGc94Vf7P"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mate.jerkovic@gmail.com",
                            FirstName = "Mate",
                            LastName = "Jerković",
                            Password = "4K3fgnoj7T3V"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hercegdragoslav@gmail.com",
                            FirstName = "Dragoslav",
                            LastName = "Herceg",
                            Password = "QsoCrT4CqErv"
                        },
                        new
                        {
                            Id = 4,
                            Email = "vukojaranka90@hotmail.com",
                            FirstName = "Ranka",
                            LastName = "Vukoja",
                            Password = "y45LRkBQjtmg"
                        },
                        new
                        {
                            Id = 5,
                            Email = "helenaknez@gmail.com",
                            FirstName = "Helena",
                            LastName = "Knežević",
                            Password = "P5LWdm9sDPnc"
                        },
                        new
                        {
                            Id = 6,
                            Email = "stipel@gmail.com",
                            FirstName = "Stjepan",
                            LastName = "Lučić",
                            Password = "bBQ3mEVXFEHc"
                        },
                        new
                        {
                            Id = 7,
                            Email = "visnja.pavlovic@gmail.com",
                            FirstName = "Višnja",
                            LastName = "Pavlović",
                            Password = "8u8sBshThMnK"
                        },
                        new
                        {
                            Id = 8,
                            Email = "alenkosar1@gmail.com",
                            FirstName = "Alen",
                            LastName = "Košar",
                            Password = "G2TJfh1BgjJo"
                        },
                        new
                        {
                            Id = 9,
                            Email = "nikolic.p@gmail.com",
                            FirstName = "Pero",
                            LastName = "Nikolić",
                            Password = "0nUda4jTo7Ar"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jankojuric99@yahoo.com",
                            FirstName = "Janko",
                            LastName = "Jurić",
                            Password = "vugpkNAzkp6G"
                        },
                        new
                        {
                            Id = 11,
                            Email = "domagoj.jerko@gmail.com",
                            FirstName = "Domagoj",
                            LastName = "Jerković",
                            Password = "b3VigXxiQJkR"
                        },
                        new
                        {
                            Id = 12,
                            Email = "lucicantonela@gmail.com",
                            FirstName = "Antonela",
                            LastName = "Lučić",
                            Password = "WZv4zYpAVszQ"
                        },
                        new
                        {
                            Id = 13,
                            Email = "adam.ivanovic2@gmail.com",
                            FirstName = "Adam",
                            LastName = "Ivanović",
                            Password = "BvHVg4EyWja6"
                        },
                        new
                        {
                            Id = 14,
                            Email = "brunopavicic@gmail.com",
                            FirstName = "Bruno",
                            LastName = "Pavičić",
                            Password = "3jiW5m92eFsb"
                        },
                        new
                        {
                            Id = 15,
                            Email = "perko.anja09@gmail.com",
                            FirstName = "Anja",
                            LastName = "Perko",
                            Password = "qkipaEkfPi2P"
                        });
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.UserItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Attendance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserItems");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            ItemId = 1,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 8,
                            ItemId = 2,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 9,
                            ItemId = 3,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 14,
                            ItemId = 1,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 11,
                            ItemId = 2,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 7,
                            ItemId = 4,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 2,
                            ItemId = 5,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 14,
                            ItemId = 6,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 1,
                            ItemId = 7,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        },
                        new
                        {
                            UserId = 10,
                            ItemId = 5,
                            Attendance = 0,
                            IsSpam = false,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.SpamAdress", b =>
                {
                    b.HasOne("Dmail.Data.Entities.Models.User", "User1")
                        .WithMany("SpamAdresses1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dmail.Data.Entities.Models.User", "User2")
                        .WithMany("SpamAdresses2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.UserItem", b =>
                {
                    b.HasOne("Dmail.Data.Entities.Models.Item", "Item")
                        .WithMany("UserItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dmail.Data.Entities.Models.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.Item", b =>
                {
                    b.Navigation("UserItems");
                });

            modelBuilder.Entity("Dmail.Data.Entities.Models.User", b =>
                {
                    b.Navigation("SpamAdresses1");

                    b.Navigation("SpamAdresses2");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
